### ISSUE TITLE
Remove nesting from $recordedEvents  

### ISSUE THREAD

**Issue by oqq** [prooph/event-store#202]
The current implementation for transactions stores all events from an aggregate in an $recordedEvents object. On every call to ```EventStore::create``` or ```EventStore::appendTo``` this object will be nested in itself.

@mikemix has provided an example where this could trigger xdebugs max nesting function level exception.
https://gist.github.com/mikemix/5ebb1726c42aeea633eca1feec1120e3

Maybe there is a better way to store this events, without an infinite nesting, which could have also positiv impact on performance.

I would suggest $recordedEvents is always an AppendIterator and got new events appended, instead of be nested on every round.

/cc @prolic

**Comment by mikemix** [comment]
I'm pleased to be of any help

**Comment by codeliner** [comment]
damn, functional programming is just not possible with PHP ;)
ok, yeah @oqq 's suggestion seems to be a good solution [recordedEvents](https://github.com/prooph/event-store/blob/master/src/EventStore.php#L47) should always be an AppendIterator so that we can avoid the nesting [here](https://github.com/prooph/event-store/blob/master/src/EventStore.php#L112)

PR would be awesome! @prolic do you agree?

**Comment by prolic** [comment]
Ok agree. Please pr to develop branch.

Am 04.11.2016 15:31 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by prolic** [comment]
see: https://github.com/prooph/event-store/releases/tag/v6.5.1
