### ISSUE TITLE
[RFC] Simplify Event Store plugin registration

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store#232]
From a user POV I think it's a little bit confusing how to register plugins. The `\Prooph\Snapshotter\SnapshotPlugin` plugin is a good example. To register a plugin in the Event Store,  *each plugin* must implement the `setUp` method.

```php
public function setUp(EventStore $eventStore)
{
    $eventStore->getActionEventEmitter()->attachListener('commit.post', [$this, 'onEventStoreCommitPost'], -1000);
}
```

Why don't we use an `attach` / `detach` method like `Zend\EventManager` has. I guess it's more intuitive to register the plugin in an Event Store instead of registering the Event Store in the plugin, which then registers the plugin in the Event Store with `$eventStore->->getActionEventEmitter()->attachListener(...)`. The Event Store should implement.

```php
public function attach($eventName, callable $listener, $priority = 1)
{
    $this->actionEventEmitter->attachListener($eventNamer, $listener, $priority);
}
```

If we use this, I guess we also don't need to expose the action event emitter with `getActionEventEmitter`.

The same behavior is used for Service Bus plugins. Maybe we should switch it too? Here is an example

```php
public function attach(ActionEventEmitter $emitter)
{
    $this->trackHandler($emitter->attachListener(MessageBus::EVENT_INITIALIZE, [$this, 'onDispatchInitialize']));
}
```

**Comment by prolic** [comment]
So if you want to register a plugin, you have to do it outside in the factory? What I really liked is EventStore->setup($plugin); and the rest is hidden.
Having only attach from outside is a worse solution imho.

**Comment by prolic** [comment]
@codeliner your thoughts?

**Comment by codeliner** [comment]
Let's use the same mechanism as we have for [service-bus](https://github.com/prooph/service-bus/blob/develop/src/MessageBus.php#L54)

- Plugin has a `attach` method which takes the AtionEventEmitter of the event store as argument
- EventStore has a `utilize` method which takes the plugin as argument

This way attaching plugins work always the same no matter the component. Thoughts?

**Comment by prolic** [comment]
sounds good. will provide a pr if none of you guys is faster :)

**Comment by prolic** [comment]
I have to take back my last comment - the issue is not solvable like this. Let me explain with the problem of dual-plugins (a plugin for command bus _and_ event store).

In message-bus we have this:
```
public function utilize(ActionEventListenerAggregate $plugin)
{
    $plugin->attach($this->getActionEventEmitter());
}
```

if we add now the same for event-store, the plugin attach() method needs to know, which action event listener is passed (from command-bus or from event-store) in order to attach correctly to the given action event emitter.

Method overloading would be great, like:
`$plugin->setup(ActionEventEmitterEventStore $eventStore)` and `$plugin->setup(MessageBus $messageBus)`.

Unfortunately PHP is lacking support of it. So we have two options I think:

1) Remove typehint in setup-method of the plugin. So we have only `$plugin->setup($something);`

In this case, we can do type checks within the plugin itself and check if we have an event store, a message bus or something else. This is kind of bad, as I really like typed parameters.

2) Have distinct named methods, like:
`$plugin->setupEventStore(ActionEventEmitterEventStore $eventStore)` and `$plugin->setupMessageBus(MessageBus $messageBus)`.

In this case I just don't like the name of the methods, but that's perhaps something we have to live with.

Any better ideas?

**Comment by codeliner** [comment]
Another option:

We make these new `availableEventNames` an explicit concept: https://github.com/prooph/common/blob/develop/src/Event/ProophActionEventEmitter.php#L34

and add a new `ActionEventEmitter::availableEventNames(): array` method to the interface so that a plugin can check if events are provided by the emitter

**Comment by prolic** [comment]
It's about the event target, not the event names. While it would work with additional if checks, it's not really a good solution

**Comment by codeliner** [comment]
```php
interface EventStorePlugin
{
    public function attachToEventStoreEmitter(ActionEventEmitter $actionEventEmitter): void;
}
```

?

**Comment by prolic** [comment]
I am working on this, will submit a PR maybe tomorrow.
