### ISSUE TITLE
ConfigurableAggregateTranslator: method_exists vs. is_callable

### ISSUE THREAD

**Issue by shochdoerfer** [prooph/event-store#235]
While experimenting with the event store I ran into the following issue - I actually wanted to propose a PR but since it involves a bit of refactoring of the unit tests I thought it might be better to discuss the issue first before pouring in a lot of work ;)

In my test setup I used the following code from the documentation to set up a repository:
```php
$this->repository = new AggregateRepository(
    $this->eventStore,
    AggregateType::fromAggregateRootClass(\My\Domain\Model\User:class),
    new ConfigurableAggregateTranslator()
);
```

Which led to the following exception:
```
Call to protected method Prooph\EventSourcing\AggregateRoot::popRecordedEvents() from context 'Prooph\EventStore\Aggregate\ConfigurableAggregateTranslator'
```

The exception is correct: The ConfigurableAggregateTranslator tried to access the popRecordedEvents() which I did not made public, it still had the `protected` visibility as defined in \Prooph\EventSourcing\AggregateRoot.

The exception I would have expected in this case is:
```
Can not pop recorded events from aggregate root My\Domain\Model\User. The AR is missing a method with name popRecordedEvents!
```

The exception did not get fired because of the usage of `method_exists`. The function will check - as the name implies - if a method exists but not if it actually can be called from the current context. Thus it might be better to rely on a `is_callable` check. `is_callable` will take the current context into account.

Whilst changing the code of ConfigurableAggregateTranslator by replacing every `method_exists` call with `is_callable` is simple, a few unit tests will fail and need to be fixed. The problem is that the Prophecy magic relies on the `__call()` magic method which will make `is_callable` return true for methods that do not exist. Thus instead of using mocked objects the unit tests would need to work with simple dummy objects.

Happy to provide a PR to fix the issue but as I pointed out above I wanted to get your feedback first if this problem is in fact a problem or if it is ok the way it is ;)

**Comment by codeliner** [comment]
@shochdoerfer happy new year :smile: 

good that you ask. We are working on a new major version of event-store. A first beta is already available: https://github.com/prooph/event-store/releases/tag/v7.0.0-beta1

In the new version all Aggregate stuff is removed or better moved to our prooph/event-sourcing package. I've created an issue [there](https://github.com/prooph/event-sourcing/issues/43)

I don't think a PR for current event-store version is worth the effort. Most people use event-store together with prooph/event-sourcing and use the `AggregateTranslator` provided by that package.

Anyway, thank you for the question. It showed me that we still have some todos before we can release the new versions. 
If you want to checkout the new versions you can play with the develop branch of our example app: [proophessor-do](https://github.com/prooph/proophessor-do/tree/develop)

prooph/event-store v7 will be a game changer. So it is a good idea to get comfortable with the new features today ;)

**Comment by prolic** [comment]
Still a fix for current release might be good, because we want to provide
support for a year.

Am 01.01.2017 21:55 schrieb "Alexander Miertsch" <notifications@github.com>:

@shochdoerfer <https://github.com/shochdoerfer> happy new year 😄

good that you ask. We are working on a new major version of event-store. A
first beta is already available: https://github.com/prooph/
event-store/releases/tag/v7.0.0-beta1

In the new version all Aggregate stuff is removed or better moved to our
prooph/event-sourcing package. I've created an issue there
<https://github.com/prooph/event-sourcing/issues/43>

I don't think a PR for current event-store version is worth the effort.
Most people use event-store together with prooph/event-sourcing and use the
AggregateTranslator provided by that package.

Anyway, thank you for the question. It showed me that we still have some
todos before we can release the new versions.
If you want to checkout the new versions you can play with the develop
branch of our example app: proophessor-do
<https://github.com/prooph/proophessor-do/tree/develop>

prooph/event-store v7 will be a game changer. So it is a good idea to get
comfortable with the new features today ;)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/prooph/event-store/issues/235#issuecomment-269903879>,
or mute the thread

**Comment by shochdoerfer** [comment]
@codeliner Any idea how much will change until the final release? Want to transform one of our internal apps to make use of ES but do not want to change it constantly ;)

**Comment by prolic** [comment]
The develop branch is pretty stable already. I don't expect major changes.

Am 01.01.2017 22:05 schrieb "Stephan Hochdörfer" <notifications@github.com>:

**Comment by codeliner** [comment]
same, here. already included v7-beta-1 in an app for a client that we are currently working on. 
If you start from scratch, use event-store v7 (meta package) together with the new [pdo-event-store](https://github.com/prooph/pdo-event-store) using postgres as the db backend.
Just join our chat if you have questions.

**Comment by shochdoerfer** [comment]
Back on-topic: Should I start to prepare a PR to fix this issue?

**Comment by codeliner** [comment]
@shochdoerfer would be great

**Comment by shochdoerfer** [comment]
@codeliner will do!
