### ISSUE TITLE
Provide abstract event store test

### ISSUE THREAD

**Issue by oqq** [prooph/event-store#257]
I am, as a redis event store developer, have to copy integration tests from pdo event store and hold fingers crossed that all tests would be enough.

Maybe someone could provide an abstract test case which could be used to test other implementations?

Maybe someone who really knows what should going on. ;)

**Comment by prolic** [comment]
I looked into this and this is really hard to do. Same parts are really dependent on the pdo-event-store implementation details and cannot be reused for other implementations. Some other stuff is not possible with InMemoryEventStore (just because it's in memory and not persistent).

What I can suggest, you may create a common AbstractTestCase that can be inherited from, but keep in mind, the abstract test case cannot be a complete event store test-suite, as some things are implementation dependent to test (like querying the pdo-connection, dropping / recreating tables, etc).

**Comment by prolic** [comment]
@oqq Do you want to provide this?

**Comment by oqq** [comment]
Sure.. this TestCase was not to be a full test. Only some default should be reflected.
- if I create a stream with events, load should return this events.

Its more an integration test. Every EventStore still need his own unit tests.

Yes I can get into this. With some assistance and tips from you in PRs. ;)

**Comment by prolic** [comment]
I take over.

**Comment by prolic** [comment]
transactional event store test trait and abstract projection manager test will also be added
