### ISSUE TITLE
Data too long for column 'locked_until'

### ISSUE THREAD

**Issue by basz** [prooph/event-store#279]
I get this error on my snapshot projection procosses

This happened after I upgrade PHP

```
[Prooph\EventStore\Exception\RuntimeException]                
  Error 22001. Maybe the projection table is not setup?         
  Error-Info: Data too long for column 'locked_until' at row 1  
```
the locked_untill file is NULL

**Comment by basz** [comment]
```
print $sql;
print_r([$lockUntilString, ProjectionStatus::RUNNING()->getValue(), $this->name, $nowString]);

UPDATE projections SET locked_until = ?, status = ? WHERE name = ? AND (locked_until IS NULL OR locked_until < ?);Array
(
    [0] => 2017-03-17T17:29:34.1000000
    [1] => running
    [2] => snapshot:commerce_store
    [3] => 2017-03-17T17:29:34.000000
)
```

**Comment by basz** [comment]
grr... https://3v4l.org/I2fQq

**Comment by basz** [comment]
https://bugs.php.net/bug.php?id=74258

**Comment by prolic** [comment]
is this your mentioned 7.1.3 bug?

**Comment by basz** [comment]
Yes sir

**Comment by prolic** [comment]
damn it - can we forbid 7.1.3 in composer json and give a message why maybe?

**Comment by basz** [comment]
Yeah this was it

**Comment by basz** [comment]
Ok case of korsakov. Just took 38min to forgot i already responded... yees

**Comment by sandrokeil** [comment]
We can add PHP 7.1.3 to the Composer `conflict` section or define a PHP range in `require` section, but no message is possible. This affects `master` and `develop`?

**Comment by basz** [comment]
We should do this but it is unfortunate that it is not really helpful.

I just hope it doesnt take a month before a fix is released in PHP.

**Comment by prolic** [comment]
I think only develop, but another test with v6 may be useful.

Am 18.03.2017 22:14 schrieb "Bas Kamer" <notifications@github.com>:

We should do this but it is unfortunate that it is not really helpful.

I just hope it doesnt take a month before a fix is released in PHP.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/prooph/event-store/issues/279#issuecomment-287548892>,
or mute the thread
