### ISSUE TITLE
[RFC] Remove MetadataMatcher

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#326]
Currently the main reason to use the MetadataMatcher, is when using SingleStreamStrategy, we need to provide additional information to create the SQL query and find the requested events.

I want to provide an event-store which uses http://geteventstore.com/ as backend, but then the metadata matcher gets ignored and the user will receive stuff, that he didn't expect to receive.

Therefore I think we should remove the metadata matcher completely and find another way to inject required query params for the event-store (maybe constructor injection).

**Comment by codeliner** [comment]
that's not the only use case. Wait until you see the event-store-mgmt-ui in action. It makes heavy use of the MetadataMatcher.

Use cases are fast look ups of:
- events by uuid (uuid was logged along with an error and you need to find that event)
- a list of events of a specific aggregate
- events with a certain name
- events newer/older than ...
- custom metadata assigned to events

The event-store-mgmt-ui makes it easy to query a single stream and the SingleStreamStrategy will continue to be the most used stream strategy. It works best for Postgres, ArangoDB and MongoDB (v4.0 will be compatible with event-store v7 again)

We have a couple of projects where we need those query capabilities. Removing them is impossible. We need to find another way.

Maybe we need different event store interfaces instead of different stream strategies.
- TopicStreamEventStore (optimized for SingleStreamStrategy use cases)
- AggregateStreamEventStore (optimized for OneStreamPerAggregate use cases)

Or we move the MetadataMatcher stuff to additional methods that are optional and an event store can provide the feature (if implementing a specific interface) or not.

But it looks like the whole thing gets a way to complex. Maybe we need to step back and think about the main usage scenarios of a prooph/event-store. The majority of projects will use either pdo-event-store or mongodb-event-store and in both cases together with SingleStreamStrategy.

Using Greg's Event Store is a very nice option but will not be the default for many projects. prooph/event-store v8 should keep that in mind.
