### ISSUE TITLE
[RFC] Refactor projections or add new projection styles

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#328]
We should either refactor current projections or add a new projetion style.

The projector should be able to save the projection state himself, and it should be able to query either the event-store himself or query the http-api.

I don't know yet how to build that, but it may be useful to have a competing consumers implementation for pdo-event-store as well (see https://eventstore.org/docs/dotnet-api/3.7.0/competing-consumers/)

**Comment by codeliner** [comment]
> The projector should be able to save the projection state himself

:+1: This would be similar to a Kafka consumer writing into a local store and allow us to decouple projections from a primary event store instance. With v7 this is a bit hard to achieve because the projector writes back to the primary database.

> but it may be useful to have a competing consumers implementation

With an AsyncEventStore and a projector based on reactPHP or amphp you can build something like that, but as a workaround you can simply use a message queue instead (if I understand the competing consumers feature correctly)
