### ISSUE TITLE
Document/Wiki

### ISSUE THREAD

**Issue by bweston92** [prooph/event-store#38]
I'm wanting to learn using events stores, can you provide wiki/documentation for using this package?

Also if there is any resources that you can link that would be great I've read lots from what Greg Young has said.

**Comment by codeliner** [comment]
I'm busy this weekend, but maybe I can give you some small hints so that you are able to start playing around with the event store. Did you have a look at the linked example: https://github.com/prooph/event-sourcing/blob/master/examples/quickstart.php?

Which framework are you using? Laravel? I currently only provide integration for Zend Framework 2 but it shouldn't be a problem to integrate PES with Laravel. Do you know the DDD basics like working with aggregates and repositories?

To get started you can install prooph/event-store together with [doctrine dbal adapter](https://github.com/prooph/event-store-doctrine-adapter) and prooph/event-sourcing. Set up a MySql database for a SingleStreamStrategy as described in the documentation of the adapter. 
Check out the example and let me know when you need more explanation.

**Comment by bweston92** [comment]
Thanks I will get started! I don't know much about aggregates yet but I do use repositories.

**Comment by codeliner** [comment]
If you want to get some more ideas about CQRS + ES you can have a look at the documentation of my new package [http://prooph.github.io/proophessor](http://prooph.github.io/proophessor). It integrates prooph/event-store in a ZF2 environment and uses  prooph/event-sourcing and prooph/service-bus for a full featured CQRS + ES system. The documentation should point you in the right direction.
