### ISSUE TITLE
Reduce hard dependencies on ZF2?

### ISSUE THREAD

**Issue by sandermarechal** [prooph/event-store#45]
Would it be possible to reduce the dependencies on ZF2? I am trying to integrate the event-store into Symfony2. Event-store depends on prooph/common which has hard dependencies on several ZF2 modules.

Right now, installing event-store drags in 7 zend modules as required dependencies

* zend/event-manager
* zend/json
* zend/log
* zend/math
* zend/serializer
* zend/service-manager
* zend/stdlib

Surely these aren't all required just to use the event-store in a non-ZF2 app? Can't a bunch of these be turned into "suggests"?

**Comment by codeliner** [comment]
You are right! We need to check the dependencies of prooph/common. prooph/event-store should only depend on the interfaces defined in prooph/common. But prooph/common ships also with default implementations for ZF2. However, composer suggestions should work fine. We will change that.

**Comment by codeliner** [comment]
@sandermarechal It will take some time to get rid of the dependcies (~2-3 weeks). We already cut some hard connections in the past but not all due to time constraints. We need to prepare new major versions for all related prooph/components and align documentation. But we have this on our roadmap anyway so stay tuned!

**Comment by codeliner** [comment]
[5.0-beta.1](https://github.com/prooph/event-store/releases/tag/v5.0-beta.1) ships without ZF2 dependencies.
